package com.rihla.thanaweya;
import android.app.*;import android.os.*;import android.webkit.*;import android.view.*;
public class MainActivity extends Activity{
 WebView web;
 private static final String INJECT="javascript:(function(){try{window.__rihlaFinalNavigationReserved=true;var n=document.getElementById('nav');if(n){n.__rihlaV10=true;n.__v12=true}var a=[['rihlaNavBootstrap','app-navigation-bootstrap.js'],['rihlaAIUX','aiux.js'],['rihlaSubscriptionV2','subscription-v2.js'],['rihlaAdminAccess','admin-access-v2.js'],['rihlaCoreV10','app-core-v10.js'],['rihlaSetupV13','app-setup-v13.js'],['rihlaNavHardV4','app-navigation-hard-v4.js'],['rihlaFriendChallengeV2','friend-challenge-v2.js'],['rihlaFriendChallengeEntryV1','friend-challenge-entry-v1.js'],['rihlaFriendChallengeButtonsFixV1','friend-challenge-buttons-fix-v1.js'],['rihlaFriendChallengeShareFixV2','friend-challenge-share-fix-v2.js'],['rihlaHomeLogoutSafeV2','home-logout-safe-v2.js']];function nload(i){if(i>=a.length)return;var x=a[i],id=x[0],f=x[1];if(document.getElementById(id)){nload(i+1);return}var s=document.createElement('script');s.id=id;s.onload=function(){nload(i+1)};s.onerror=function(){nload(i+1)};s.src='file:///android_asset/www/'+f;document.body.appendChild(s)}nload(0)}catch(e){console.log('module loader',e)}})();";
 private static final String BACK="javascript:(function(){try{var r=window.rihlaBack?window.rihlaBack():'exit';if(window.Android&&Android.backResult)Android.backResult(r)}catch(e){if(window.Android&&Android.backResult)Android.backResult('exit')}})();";
 @Override public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);web.setLayoutParams(new ViewGroup.LayoutParams(-1,-1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMediaPlaybackRequiresUserGesture(false);web.addJavascriptInterface(new AppBridge(this),"Android");web.setWebViewClient(new WebViewClient(){@Override public void onPageFinished(WebView v,String u){super.onPageFinished(v,u);v.evaluateJavascript(INJECT,null);}});setContentView(web);web.loadUrl("file:///android_asset/www/index.html");}
 @Override public void onBackPressed(){web.evaluateJavascript(BACK,null);}
 public static class AppBridge{private final Activity a;AppBridge(Activity a){this.a=a;}@JavascriptInterface public void backResult(String r){if("exit".equals(r))a.finishAndRemoveTask();}@JavascriptInterface public void exitApp(){a.runOnUiThread(()->a.finishAndRemoveTask());}}
}
